CREATE TABLE ALL_CUSTOMER
(
  CODE           VARCHAR2(50 BYTE),
  CUSTOMER_NAME  VARCHAR2(100 BYTE),
  CREDIT_LIMIT   NUMBER,
  PHONE          NUMBER,
  ADDRESS        VARCHAR2(200 BYTE),
  BRANCH         VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE ALL_PRODUCT
(
  CODE          VARCHAR2(50 BYTE),
  PRODUCT_NAME  VARCHAR2(200 BYTE),
  UNIT_PRICE    NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE DATE_ENTRY
(
  START_DATE  DATE,
  END_DATE    DATE,
  DATE_ID     NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE DESIGNATION
(
  DESIGNATION  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE EMP_ADDRESS_INFORMATION
(
  PRESENT_HOUSE         VARCHAR2(100 BYTE),
  PRESENT_VILLAGE       VARCHAR2(50 BYTE),
  PRESENT_UNION         VARCHAR2(50 BYTE),
  PRESENT_POSTOFFICE    VARCHAR2(50 BYTE),
  PRESENT_POSTCODE      NUMBER,
  PRESENT_THANA         VARCHAR2(50 BYTE),
  PRESENT_DISTRICT      VARCHAR2(50 BYTE),
  PRESENT_DIVISION      VARCHAR2(50 BYTE),
  PRESENT_COUNTRY       VARCHAR2(50 BYTE),
  PERMANENT_HOUSE       VARCHAR2(50 BYTE),
  PERMANENT_VILLAGE     VARCHAR2(50 BYTE),
  PERMANENT_UNION       VARCHAR2(50 BYTE),
  PERMANENT_POSTOFFICE  VARCHAR2(50 BYTE),
  PERMANENT_POSTCODE    NUMBER,
  PERMANENT_THANA       VARCHAR2(50 BYTE),
  PERMANENT_DISTRICT    VARCHAR2(50 BYTE),
  PERMANENT_DIVISION    VARCHAR2(50 BYTE),
  PERMANENT_COUNTRY     VARCHAR2(50 BYTE),
  COMMON_CODE           NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE EMP_ATTENDANCE_INFORMATION
(
  ATTENDANCE_ID    NUMBER,
  EMPLOYEE_ID      VARCHAR2(50 BYTE),
  ATTENDANCE_DATE  DATE,
  TIME_IN          DATE,
  TIME_OUT         DATE,
  ABSENCE_REASON   VARCHAR2(50 BYTE),
  LATE             VARCHAR2(10 BYTE),
  OVERTIME         VARCHAR2(10 BYTE),
  STATUS           VARCHAR2(20 BYTE),
  LEAVE_ID         VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE EMP_BASIC_INFORMATION
(
  EMP_CODE         VARCHAR2(50 BYTE),
  EMP_NAME         VARCHAR2(100 BYTE),
  DESIGNATION      VARCHAR2(100 BYTE),
  DOB              DATE,
  AGE              CHAR(50 BYTE),
  NID_NUMBER       NUMBER,
  PERSONAL_PHONE   VARCHAR2(100 BYTE),
  CORPORATE_PHONE  VARCHAR2(100 BYTE),
  OFFICE_EMAIL     VARCHAR2(100 BYTE),
  PERSONAL_EMAIL   VARCHAR2(100 BYTE),
  SERVICE_LENGTH   VARCHAR2(100 BYTE),
  COMMON_CODE      NUMBER,
  EMP_IMAGE        BLOB,
  LAST_UPDATED     DATE,
  IS_DELETED       NUMBER(1)                    DEFAULT 0,
  CREATED_AT       DATE                         DEFAULT SYSDATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE EMP_EMPLOYMENT_INFORMATION
(
  EMP_TYPE           VARCHAR2(50 BYTE),
  JOINING_DATE       DATE,
  DEPARTMENT         VARCHAR2(50 BYTE),
  SECTION            VARCHAR2(50 BYTE),
  ATTENDANCE_CARDID  NUMBER,
  CONFIRMATION_DATE  DATE,
  STATUS             VARCHAR2(50 BYTE),
  COMMON_CODE        NUMBER,
  PF                 VARCHAR2(50 BYTE),
  BRANCH             VARCHAR2(30 BYTE),
  SHIFT              VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE EMP_LIST
(
  EMP_CODE              VARCHAR2(50 BYTE),
  EMP_NAME              VARCHAR2(50 BYTE),
  EMP_STATUS            VARCHAR2(20 BYTE),
  EMP_BRANCH            VARCHAR2(50 BYTE),
  EMP_DEPARTMENT        VARCHAR2(30 BYTE),
  EMP_DESIGNATION       VARCHAR2(50 BYTE),
  EMP_JOINING_DATE      DATE,
  EMP_SHIFT             VARCHAR2(30 BYTE),
  EMP_PAYSCALE          VARCHAR2(30 BYTE),
  EMP_SALARY            NUMBER,
  EMP_PAYROLL_SCHEDULE  VARCHAR2(50 BYTE),
  EMP_CREATED_AT        DATE                    DEFAULT SYSDATE,
  EMP_IS_DELETED        NUMBER                  DEFAULT 0,
  LAST_UPDATED          DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE EMP_PERSONAL_INFORMATION
(
  FATHER_NAME      VARCHAR2(100 BYTE),
  MOTHER_NAME      VARCHAR2(100 BYTE),
  RELIGION         VARCHAR2(50 BYTE),
  NATIONALITY      VARCHAR2(50 BYTE),
  WEIGHT           NUMBER,
  GENDER           VARCHAR2(30 BYTE),
  BLOOD_GROUP      VARCHAR2(20 BYTE),
  MARITAL_STATUS   VARCHAR2(20 BYTE),
  SPOUSE_NAME      VARCHAR2(50 BYTE),
  CHILDREN_NUMBER  NUMBER,
  HEIGHT           NUMBER,
  COMMON_CODE      NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE EMP_SALARY_ACCOUNT_INFORMATION
(
  PAYSCALE             VARCHAR2(50 BYTE),
  BASIC_SALARY         NUMBER,
  BANK_NAME            VARCHAR2(50 BYTE),
  START_DATE           DATE,
  PAYGRADE             VARCHAR2(50 BYTE),
  GROSS_SALARY         NUMBER,
  ACCOUNT_NAME         VARCHAR2(50 BYTE),
  LAST_INCREMENT_DATE  DATE,
  PAYMENT_MODE         VARCHAR2(50 BYTE),
  PAYROLL_NAME         VARCHAR2(50 BYTE),
  ACCOUNT_NUMBER       NUMBER,
  INCREMENT_AMOUNT     NUMBER,
  COMMON_CODE          NUMBER,
  LAST_UPDATED         DATE,
  PF                   VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE FIXED_YEARLY_LEAVE_BALANCE
(
  AL   NUMBER,
  SL   NUMBER,
  CL   NUMBER,
  SPL  NUMBER,
  LWP  NUMBER,
  TL   NUMBER,
  WH   NUMBER,
  BD   NUMBER,
  FA   NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE HOLIDAYS
(
  HOLIDAY_ID    NUMBER,
  HOLIDAY_DATE  DATE,
  HOLIDAY_NAME  VARCHAR2(100 BYTE),
  DESCRIPTION   VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE LEAVE_APPLICATION
(
  EMP_NAME          VARCHAR2(100 BYTE),
  LEAVE_TYPE        VARCHAR2(50 BYTE),
  START_LEAVE       DATE,
  END_LEAVE         DATE,
  LEAVE_DAYS        NUMBER,
  PF                VARCHAR2(50 BYTE),
  STATUS            VARCHAR2(50 BYTE),
  LEAVE_ID          VARCHAR2(20 BYTE),
  LEAVE_APPLY_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE LEAVE_APPROVED
(
  ID                  VARCHAR2(50 BYTE),
  STATUS              VARCHAR2(50 BYTE),
  EMP_NAME            VARCHAR2(100 BYTE),
  LEAVE_TYPE          VARCHAR2(50 BYTE),
  START_DATE          DATE,
  END_DATE            DATE,
  LEAVE_DAYS          NUMBER,
  SN                  NUMBER,
  LEAVE_ID            VARCHAR2(50 BYTE),
  LEAVE_APPROVE_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE LOGIN
(
  USERNAME          VARCHAR2(50 BYTE),
  PASSWORD          VARCHAR2(50 BYTE),
  CONFIRM_PASSWORD  VARCHAR2(50 BYTE),
  NAME              VARCHAR2(60 BYTE),
  TYPE              VARCHAR2(30 BYTE),
  EMPLOYEE_CODE     VARCHAR2(30 BYTE),
  ASSIGN_ROLE       VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE MANPOWER_REQUISITION
(
  MAN_REQ_ID                NUMBER,
  DOR                       DATE,
  DOMR                      DATE,
  DEPT                      VARCHAR2(50 BYTE),
  RECRUITMENT_TYPE          VARCHAR2(50 BYTE),
  VACANCY_CAUSE             VARCHAR2(100 BYTE),
  REPLACEMENT_PF            NUMBER,
  UNAME                     VARCHAR2(60 BYTE),
  OLD_DESIGNATION           VARCHAR2(50 BYTE),
  LAST_SALARY               NUMBER,
  OLD_SECTION               VARCHAR2(50 BYTE),
  OLD_LINE                  VARCHAR2(50 BYTE),
  DEPT_MAN_EXIST            NUMBER,
  SEC_MAN_EXIST             NUMBER,
  REQUIRED_MAN              NUMBER,
  JOB_LOCATION              VARCHAR2(50 BYTE),
  CRITICAL_IMPACT_POSITION  VARCHAR2(200 BYTE),
  DESIGNATION               VARCHAR2(50 BYTE),
  SECTION                   VARCHAR2(50 BYTE),
  LINE                      VARCHAR2(50 BYTE),
  APPOINTMENT_TYPE          VARCHAR2(50 BYTE),
  SALARY_RANGE              VARCHAR2(60 BYTE),
  AGE_LIMIT                 NUMBER,
  EDU_QUALIFICATION         VARCHAR2(100 BYTE),
  EXPERIENCE                NUMBER,
  JOB_DESCRIPTION1          VARCHAR2(200 BYTE),
  JOB_DESCRIPTION2          VARCHAR2(200 BYTE),
  JOB_DESCRIPTION3          VARCHAR2(200 BYTE),
  JOB_DESCRIPTION4          VARCHAR2(200 BYTE),
  JOB_DESCRIPTION5          VARCHAR2(200 BYTE),
  PROFESSIONAL_SKILL1       VARCHAR2(200 BYTE),
  PROFESSIONAL_SKILL2       VARCHAR2(200 BYTE),
  PROFESSIONAL_SKILL3       VARCHAR2(200 BYTE),
  PROFESSIONAL_SKILL4       VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE OFFER_LATTER
(
  CURRENT_DATE      DATE,
  USERNAME          VARCHAR2(50 BYTE),
  VILLAGE           VARCHAR2(50 BYTE),
  PO                VARCHAR2(50 BYTE),
  PS                VARCHAR2(50 BYTE),
  DISTRICT          VARCHAR2(50 BYTE),
  PHONE             VARCHAR2(50 BYTE),
  EMAIL             VARCHAR2(50 BYTE),
  POSITION          VARCHAR2(50 BYTE),
  DOJ               DATE,
  PROBATION_PERIOD  NUMBER,
  EMP_ID            VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE ORDERED_CUSTOMERS
(
  CUSTOMER_CODE    VARCHAR2(50 BYTE),
  INVOICE_DATE     DATE,
  DELIVERY_DATE    DATE,
  INVOICE_CREATER  VARCHAR2(50 BYTE),
  ORDER_NUMBER     NUMBER,
  NET_VALUE        NUMBER,
  TOTAL_VALUE      NUMBER,
  CUSTOMER_NAME    VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE ORDERED_PRODUCTS
(
  ORDER_NUMBER  NUMBER,
  PRODUCT_CODE  VARCHAR2(50 BYTE),
  QTY           NUMBER,
  UNIT_PRICE    NUMBER,
  PRODUCT_NAME  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE PAYSCALEPAYGRADE
(
  PAYSCALE  VARCHAR2(50 BYTE),
  PAYGRADE  VARCHAR2(50 BYTE),
  AMOUNT    NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE PROMOTION_LATTER
(
  CURRENT_DATE    DATE,
  PROMOTION_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE SALARY_INCREMENT
(
  PF                VARCHAR2(50 BYTE),
  USERNAME          VARCHAR2(100 BYTE),
  TYPE              VARCHAR2(50 BYTE),
  DESIGNATION       VARCHAR2(50 BYTE),
  PAYSCALE          VARCHAR2(50 BYTE),
  PAYGRADE          VARCHAR2(50 BYTE),
  BASIC_SALARY      NUMBER,
  GROSS_SALARY      NUMBER,
  INCREMENT_VALUE   NUMBER,
  EFFECTIVE_DATE    DATE,
  TRANSACTION_CODE  NUMBER,
  NEW_GROSS         NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;
